version: '3'
services:
  vault:
    image: vault
    container_name: vault
    ports:
      - "8200:8200"
    restart: always
    volumes:
      - ./server.hcl:/vault/config/server.hcl
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/server.hcl
